import test from 'node:test';import assert from 'node:assert/strict';import {proposedCommandPrefix} from '../apps/desktop/command-approvals.mjs';import {commandRiskInstructions} from '../apps/desktop/command-policy.mjs';
const request=prefix=>({method:'item/commandExecution/requestApproval',params:{kind:'command',command:'git status --short',cwd:'/workspace',threadId:'t',turnId:'x',proposedExecpolicyAmendment:prefix}});
test('prefix approval uses validated runtime argv rather than command string prefix',()=>{assert.deepEqual(proposedCommandPrefix(request(['git','status'])),['git','status']);assert.deepEqual(proposedCommandPrefix(request(['npm','run','build'])),['npm','run','build']);for(const prefix of [null,[],['git'],['bash','-c'],['/bin/zsh','-lc'],['python3','-c'],['sudo','git'],['env','git'],['node','-e'],['git','status\n'],['git',3]])assert.equal(proposedCommandPrefix(request(prefix)),null);});
test('non-command/network approvals do not expose prefix grants',()=>{const r=request(['git','status']);for(const value of [{...r,method:'item/fileChange/requestApproval'},{...r,params:{...r.params,kind:'writeStdin'}},{...r,params:{...r.params,networkApprovalContext:{host:'example.com'}}}])assert.equal(proposedCommandPrefix(value),null);});
test('risk instructions distinguish normal sandbox work from privilege and side effect escalation',()=>{for(const text of ['直接执行','不联网','require_escalated','GUI','删除','安装钩子','重定向','用户授权'])assert.ok(commandRiskInstructions.includes(text));});

import {TaskPrefixRules} from '../apps/desktop/task-prefix-rules.mjs';import {mkdtemp,readFile,writeFile,mkdir,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
test('task prefix journal restores existing rules and removes new rules after crash',async()=>{const dir=await mkdtemp(join(tmpdir(),'prefix-journal-'));try{const rules=new TaskPrefixRules(dir);await Promise.all([rules.begin(),rules.begin()]);await mkdir(join(dir,'rules'));await writeFile(rules.rule,'new grant');await new TaskPrefixRules(dir).restore();await assert.rejects(readFile(rules.rule),{code:'ENOENT'});await writeFile(rules.rule,'existing rule');await rules.begin();await writeFile(rules.rule,'existing rule\nnew grant');await rules.begin();await rules.restore();assert.equal(await readFile(rules.rule,'utf8'),'existing rule');}finally{await rm(dir,{recursive:true,force:true});}});
test('malformed prefix journal fails closed without touching rule file',async()=>{const dir=await mkdtemp(join(tmpdir(),'prefix-journal-'));try{const rules=new TaskPrefixRules(dir);await mkdir(join(dir,'rules'));await writeFile(rules.rule,'keep');await writeFile(rules.backup,'{"version":2}');await assert.rejects(rules.restore());assert.equal(await readFile(rules.rule,'utf8'),'keep');}finally{await rm(dir,{recursive:true,force:true});}});
