import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import {CredentialVault} from '../apps/desktop/credentials.mjs';
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'vault-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const key=randomBytes(32);const crypto={isEncryptionAvailable:()=>true,getSelectedStorageBackend:()=> 'gnome_libsecret',encryptString(value){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([c.update(value,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),data]);},decryptString(data){const d=createDecipheriv('aes-256-gcm',key,data.subarray(0,12));d.setAuthTag(data.subarray(12,28));return Buffer.concat([d.update(data.subarray(28)),d.final()]).toString();}};return {dir,crypto,vault:new CredentialVault(dir,crypto,{DEEPSEEK_API_KEY:'environment-fixture-key'})};}
test('credential encryption, reload, precedence, status redaction and deletion fallback',async t=>{const {dir,crypto,vault}=await fixture(t);const secret='fixture-sensitive-key';await vault.save('deepseek-chat',secret);assert.equal((await readFile(vault.name('deepseek-chat'))).includes(secret),false);assert.equal((await stat(vault.name('deepseek-chat'))).mode&0o777,0o600);assert.equal(await new CredentialVault(dir,crypto).key('deepseek-chat'),secret);assert.equal(JSON.stringify(await vault.status()).includes(secret),false);await vault.remove('deepseek-chat');assert.equal(await vault.key('deepseek-chat'),'environment-fixture-key');});
test('corrupt credential is isolated and repairable without environmental fallback',async t=>{const {vault}=await fixture(t);await writeFile(vault.name('deepseek-chat'),'corrupt');assert.equal((await vault.environment()).DEEPSEEK_API_KEY,'');assert.match((await vault.status()).models[0].error,/解密/);await vault.save('deepseek-chat','replacement-fixture');assert.equal(await vault.key('deepseek-chat'),'replacement-fixture');});
test('unavailable encryption rejects save and retains environment support',async t=>{const {vault,crypto}=await fixture(t);crypto.isEncryptionAvailable=()=>false;await assert.rejects(vault.save('deepseek-chat','fixture-key'),/暂不可用/);assert.equal(await vault.key('deepseek-chat'),'environment-fixture-key');});
test('credential validation rejects unsupported id and malformed secret',async t=>{const {vault}=await fixture(t);await assert.rejects(vault.save('../escape','fixture-key'),/未知/);for(const key of ['',null,'spaces are invalid'])await assert.rejects(vault.save('deepseek-chat',key),/格式/);});
