import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {headProbe} from '../apps/desktop/security/executor.mjs';
import {SecurityDrafts} from '../apps/desktop/security/drafts.mjs';
import {auditHeaders} from '../apps/desktop/security/http-audit.mjs';
async function fixture(t,handler){const server=createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const url=`http://127.0.0.1:${server.address().port}/`;return {url,config:new SecurityDrafts().prepare('/tmp',url).config};}
const args=f=>({...f,signal:new AbortController().signal,reserve:async()=>{}});
test('S2-B headers redact unknown values and bound retained fields',()=>{const a=auditHeaders({'set-cookie':['session=SECRET'],'x-private':'SECRET',server:'x'.repeat(1200)});assert(!JSON.stringify(a).includes('SECRET'));assert.equal(a.headers.server.length,1024);assert.deepEqual(a.truncatedHeaders,['server']);});
test('S2-B redirects have separately recorded responses with no cookie or location secret',async t=>{let hits=0;const f=await fixture(t,(q,r)=>{hits++;if(q.url==='/'){r.writeHead(302,{'location':'/next','set-cookie':'sid=SECRET'});}r.end();});const evidence=[];await headProbe({...args(f),record:async v=>evidence.push(v)});assert.equal(hits,2);assert.equal(evidence.length,2);assert.equal(evidence[0].redirect.value,'[REDACTED]');assert.equal(evidence[0].headers['set-cookie'],'[REDACTED]');assert(!JSON.stringify(evidence).includes('SECRET'));assert(evidence.every(e=>e.durationMs>=0&&e.body.reason==='HEAD'));});
test('S2-B reset and timeout persist terminal request outcomes',async t=>{for(const reset of [true,false]){const f=await fixture(t,(q,r)=>{if(reset)q.socket.destroy();});f.config.budget.timeoutMs=100;const evidence=[];await assert.rejects(headProbe({...args(f),record:async v=>evidence.push(v)}));assert.equal(evidence.length,1);assert.equal(evidence[0].outcome,'network-error');assert.equal(evidence[0].capture,'no-response-headers');}});
test('S2-B response audit failure prevents redirect follow-up',async t=>{let hits=0;const f=await fixture(t,(q,r)=>{hits++;r.writeHead(302,{location:'/next'});r.end();});await assert.rejects(headProbe({...args(f),record:async()=>{throw Error('disk full');}}),/disk full/);assert.equal(hits,1);});
test('S2-B cancellation records aborted request without raw exception text',async t=>{let observed;const ready=new Promise(r=>observed=r);const f=await fixture(t,()=>observed());const c=new AbortController();const evidence=[];const p=headProbe({...args(f),signal:c.signal,record:async v=>evidence.push(v)});await ready;c.abort(Error('SECRET'));await assert.rejects(p);assert.equal(evidence[0].outcome,'aborted');assert(!JSON.stringify(evidence).includes('SECRET'));});
