import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {mkdtemp,rm,readFile,writeFile,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {defaultEngagement,engagementSchema,checkScope} from '../apps/desktop/security/scope.mjs';import {SecurityService} from '../apps/desktop/security/service.mjs';import {headProbe} from '../apps/desktop/security/executor.mjs';
const config=(targets,extra={})=>engagementSchema({...defaultEngagement(),enabled:true,targets,...extra});
test('S1 scope: exact domain, wildcard, path boundary, exclusions, protocol, time and credentials',()=>{
 const c=config([{host:'example.com',path:'/api'},{host:'*.example.org'}],{exclude:[{host:'example.com',path:'/api/private'}]});
 checkScope(c,'https://example.com/api/a');checkScope(c,'https://a.example.org/');
 for(const u of ['https://example.com.attacker.com/api','https://example.com/api2','https://example.com/api/private/one','https://example.org/','http://example.com/api','https://example.com:444/api','https://user:pass@example.com/api','https://example.com/api?q=secret','https://example.com/api/%2fprivate','https://example.com/api/%252fprivate'])assert.throws(()=>checkScope(c,u));
 assert.throws(()=>checkScope({...c,expiresAt:'2000-01-01'},'https://example.com/api'));
 assert.throws(()=>engagementSchema({...c,budget:{...c.budget,concurrency:2}}));
});
test('S1 DNS: all addresses checked, IP exclusion wins, explicit private IPv4/IPv6 CIDR',()=>{
 const c=config([{host:'example.com'}]);assert.throws(()=>checkScope(c,'https://example.com/',{addresses:[{address:'1.1.1.1'},{address:'127.0.0.1'}]}));
 const local=config([{host:'example.com'},{host:'127.0.0.0/8'},{host:'::1/128'}]);checkScope(local,'https://example.com/',{addresses:[{address:'127.0.0.1'}]});checkScope(local,'https://[::1]/',{addresses:[{address:'::1'}]});
 assert.throws(()=>checkScope({...local,exclude:[{host:'127.0.0.1',protocols:['https'],ports:[443],path:'/'}]},'https://example.com/',{addresses:[{address:'127.0.0.1'}]}));
});
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'coagent-security-'));const hits=[];const server=createServer((q,r)=>{hits.push({url:q.url,headers:q.headers,method:q.method});if(q.url==='/stall')return;if(q.url==='/redirect'){r.writeHead(302,{location:'/done','set-cookie':'secret=must-not-log'});r.end();return;}if(q.url==='/outside'){r.writeHead(302,{location:'http://127.0.0.1:1/'});r.end();return;}if(q.url==='/loop'){r.writeHead(302,{location:'/loop'});r.end();return;}r.setHeader('set-cookie','secret=must-not-log');r.end('sensitive-body');});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await rm(root,{recursive:true,force:true});});const port=server.address().port;const c=config([{host:'127.0.0.1',protocols:['http'],ports:[port]}]);c.budget.requestsPerSecond=10;const service=new SecurityService(root);await service.save(root,c);return {root,hits,service,c,base:`http://127.0.0.1:${port}`};}
async function run(f,path){await f.service.start(f.root,{tool:'http-head',urls:[f.base+path],confirmed:true});await f.service.active?.done;return (await f.service.state(f.root)).runs[0];}
test('S1 execution: HEAD, redirect budget, evidence hashes and no cookies/body',async t=>{const f=await fixture(t);const r=await run(f,'/redirect');assert.equal(r.status,'completed');assert.equal(r.requests,2);assert.equal(r.evidenceCount,2);assert.ok(f.hits.every(h=>h.method==='HEAD'&&!h.headers.cookie&&!h.headers.authorization));const events=(await readFile(join(r.directory,'events.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);for(const e of events.filter(e=>e.type==='evidence')){const data=await readFile(join(r.directory,e.file));assert.equal(createHash('sha256').update(data).digest('hex'),e.sha256);assert.doesNotMatch(data.toString(),/sensitive-body|must-not-log/);}assert.equal((await new SecurityService(f.root).config(f.root)).config.enabled,true);});
test('S1 registry and explicit plan approval reject before network',async t=>{const f=await fixture(t);for(const args of [{tool:'shell',confirmed:true,urls:[f.base]},{tool:'http-head',confirmed:false,urls:[f.base]},{tool:'http-head',confirmed:true,urls:['https://outside.test/']}])await assert.rejects(f.service.start(f.root,args));assert.equal(f.hits.length,0);});
test('S1 redirects outside scope and loops fail before another request',async t=>{const f=await fixture(t);assert.equal((await run(f,'/outside')).status,'failed');assert.equal(f.hits.length,1);const r=await run(f,'/loop');assert.equal(r.status,'failed');assert.equal(f.hits.length,2);});
test('S1 request budget also applies to redirects',async t=>{const f=await fixture(t);f.c.budget.maxRequests=1;await f.service.save(f.root,f.c);const r=await run(f,'/redirect');assert.equal(r.status,'failed');assert.equal(r.requests,1);assert.equal(f.hits.length,1);});
test('S1 cancellation aborts outstanding request and never launches next URL',async t=>{const f=await fixture(t);await f.service.start(f.root,{tool:'http-head',confirmed:true,urls:[f.base+'/stall',f.base+'/done']});await assert.rejects(f.service.save(f.root,f.c));for(let i=0;i<100&&!f.hits.length;i++)await new Promise(r=>setTimeout(r,10));await f.service.stop();const r=(await f.service.state(f.root)).runs[0];assert.equal(r.status,'interrupted');assert.equal(f.hits.length,1);});
test('S1 stopping during initialization prevents all network requests',async t=>{const f=await fixture(t);const start=f.service.start(f.root,{tool:'http-head',confirmed:true,urls:[f.base]});await f.service.stop();await start;await f.service.active?.done;assert.equal(f.hits.length,0);assert.equal((await f.service.state(f.root)).runs[0].status,'interrupted');});
test('S1 deadline aborts, rate budget separates requests',async t=>{const f=await fixture(t);f.c.budget.maxDurationMs=150;await f.service.save(f.root,f.c);assert.equal((await run(f,'/stall')).status,'interrupted');f.c.budget.maxDurationMs=3000;f.c.budget.requestsPerSecond=2;await f.service.save(f.root,f.c);const start=Date.now();assert.equal((await run(f,'/redirect')).status,'completed');assert.ok(Date.now()-start>=490);});
test('S1 crash recovery preserves evidence without replay',async t=>{const f=await fixture(t);const dir=join(f.service.directory(f.root),'runs','crashed');await mkdir(dir,{recursive:true});await writeFile(join(dir,'run.json'),JSON.stringify({id:'crashed',status:'running',requests:1}));const state=await f.service.state(f.root);assert.equal(state.runs[0].status,'interrupted');assert.equal(f.hits.length,0);});
test('S1 executor pins DNS resolution to vetted address',async t=>{const f=await fixture(t);f.c.targets.push({host:'fixture.invalid',protocols:['http'],ports:[+new URL(f.base).port],path:'/'});let lookups=0;const records=[];await headProbe({url:f.base.replace('127.0.0.1','fixture.invalid'),config:f.c,signal:new AbortController().signal,reserve:async()=>{},record:async r=>records.push(r),resolve:async()=>{lookups++;return [{address:'127.0.0.1',family:4}];}});assert.equal(lookups,1);assert.equal(f.hits.length,1);assert.equal(records[0].address,'127.0.0.1');});
test('S1 restored configuration requires review and resave before execution',async t=>{const f=await fixture(t);await f.service.save(f.root,{...f.c,budget:{...f.c.budget,maxRequests:5}});await writeFile(join(f.service.directory(f.root),'engagement.json'),'broken');await assert.rejects(f.service.start(f.root,{tool:'http-head',confirmed:true,urls:[f.base]}),/备份恢复/);assert.equal(f.hits.length,0);const restored=await f.service.config(f.root);assert.ok(restored.warning);assert.equal(restored.config.enabled,false);assert.equal((await new SecurityService(f.root).config(f.root)).config.enabled,false);await f.service.save(f.root,{...restored.config,enabled:true});assert.equal((await run(f,'/')).status,'completed');});
test('S1 concurrent configuration save blocks test start',async t=>{const f=await fixture(t);const saving=f.service.save(f.root,{...f.c,budget:{...f.c.budget,maxRequests:5}});await assert.rejects(f.service.start(f.root,{tool:'http-head',confirmed:true,urls:[f.base]}),/配置保存/);await saving;assert.equal(f.hits.length,0);});
