import React,{useState} from 'react';
export function ApprovalCard({approval,count,onDecision}){
 const [pending,P]=useState(false),[error,E]=useState('');
 async function decide(decision,scope='once'){P(true);E('');try{await onDecision(decision,scope);}catch(e){E(e.message);}finally{P(false);}}
 const command=approval.method==='item/commandExecution/requestApproval',file=approval.method==='item/fileChange/requestApproval';
 return <section className="approval approval-card" role="region" aria-label="操作审批" aria-busy={pending}><div className="approval-heading"><span className="approval-icon">{command?'⌘':file?'▤':'◇'}</span><div><strong>{command?'允许运行此命令？':file?'允许这些文件变更？':'允许执行此操作？'}</strong><small>{count>1?`${count} 项待审批 · `:''}确认后才会继续执行</small></div></div>{approval.reason&&<p className="approval-reason">{approval.reason}</p>}{approval.command&&<pre className="approval-command">{approval.command}</pre>}{approval.cwd&&<div className="approval-path" title={approval.cwd}>工作目录 <code>{approval.cwd}</code></div>}{!approval.command&&<pre>{approval.message||approval.method}</pre>}{(approval._meta?.tool_params||approval.changes)&&<details><summary>查看操作详情</summary><pre>{JSON.stringify(approval._meta?.tool_params||approval.changes,null,2)}</pre></details>}
 {(approval.commandPrefix||approval.commandSimilarAvailable)&&<details className="approval-scope"><summary>本次任务的授权选项</summary>{approval.commandPrefix&&<div><code>{JSON.stringify(approval.commandPrefix)}</code><p>匹配此前缀的命令可能在沙盒外执行。仅本次任务有效，停止或下一轮任务清除。</p><button type="button" disabled={pending} onClick={()=>decide('accept','task-command-prefix')}>本次任务允许此前缀</button></div>}{approval.commandSimilarAvailable&&<div><p>仅相同命令、目录和权限上下文免重复审批，参数变化仍需确认。</p><button type="button" disabled={pending} onClick={()=>decide('accept','task-command-similar')}>本次任务允许同类命令</button></div>}</details>}
 {error&&<p role="alert" className="error">{error}</p>}<div className="approval-actions"><button type="button" className="approval-deny" disabled={pending} onClick={()=>decide('decline')}>拒绝</button><button type="button" className="approval-allow" disabled={pending} onClick={()=>decide('accept')}>{pending?'处理中…':'允许此次操作'}</button></div></section>;
}
