import React,{useState,useEffect,useRef} from 'react';
const labels={'transport-completed':'传输完成','provider-error':'服务商错误',failed:'调用失败','cancelled-or-timeout':'取消或超时',unrecorded:'结果未记录'};
export function AuditPanel({workspace}){
 const [data,S]=useState({records:[]}),[all,A]=useState(false),[filter,F]=useState('all'),[selected,I]=useState(null),[error,E]=useState(''),[loading,L]=useState(false);const seq=useRef(0);
 async function refresh(){const n=++seq.current;L(true);E('');try{const value=await window.coagent.call('audit:list',{allProjects:all});if(n===seq.current){S(value);I(id=>value.records.some(r=>r.requestId===id)?id:null);}}catch(e){if(n===seq.current){S({records:[]});E(e.message);}}finally{if(n===seq.current)L(false);}}
 useEffect(()=>{S({records:[]});I(null);refresh();return()=>{seq.current++;};},[workspace,all]);
 const rows=data.records.filter(r=>filter==='all'||r.outcome===filter);const row=rows.find(r=>r.requestId===selected);const value=row?.result||row?.intent;
 return <div className="audit-panel"><div className="audit-toolbar"><h3>模型审计</h3><button disabled={loading} onClick={refresh}>{loading?'读取中…':'刷新'}</button></div><p className="muted">仅调用元数据，不含提示词、输出正文或密钥。传输完成不代表任务成功。</p><div className="audit-filters"><select aria-label="审计项目范围" value={all?'all':'current'} onChange={e=>A(e.target.value==='all')}><option value="current">当前项目</option><option value="all">全部项目</option></select><select aria-label="审计结果筛选" value={filter} onChange={e=>F(e.target.value)}><option value="all">全部结果</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{error&&<p role="alert">{error}</p>}{data.unreadable>0&&<p role="status">{data.unreadable} 个审计文件损坏或不可读，已跳过。</p>}{data.truncated&&<p role="status">记录较多：最多检查 2000 个文件、展示 100 条；当前列表不保证覆盖最新记录。</p>}<div className="audit-scroll">{!loading&&!rows.length&&<p className="muted">暂无匹配的审计记录</p>}<div className="audit-records">{rows.map(r=><button key={r.requestId} className={selected===r.requestId?'selected':''} onClick={()=>I(r.requestId)}><strong>{labels[r.outcome]}</strong><time>{new Date(r.time).toLocaleString()}</time><small>{(r.result||r.intent).protocol} · {r.requestId.slice(0,8)}</small></button>)}</div>{row&&<section className="audit-detail" aria-label="审计详情"><h4>请求详情</h4><dl>{[['请求 ID',row.requestId],['网关会话',value.gatewaySessionId],['线程 ID',value.context.threadId],['轮次 ID',value.context.turnId],['项目哈希',value.context.workspaceHash],['服务配置指纹',value.providerFingerprint],['HTTP 状态',row.result?.upstreamStatus],['耗时',row.result?.durationMs===undefined?undefined:row.result.durationMs+' ms'],['意图记录',row.intent?.time],['结果记录',row.result?.time]].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v??'未记录'}</dd></React.Fragment>)}</dl>{!row.result&&<p>仅有发送意图，可能仍在执行、发生崩溃或结果写入失败；请勿据此自动重试。</p>}{!row.intent&&<p>意图文件缺失或不可读，关联记录不完整。</p>}</section>}</div></div>;
}
