import React,{useState,useEffect,useRef} from 'react';
const api=window.coagent;
export function Composer({workspace,busy,prompt,onPrompt,onSubmit,children,onMenuChange}){
 const [securityMode,Q]=useState(false);
 const [files,F]=useState([]),[selectedSkills,K]=useState([]),[plugins,P]=useState([]),[menu,M]=useState(false),[tab,T]=useState('root'),[catalog,C]=useState({skills:[],plugins:[]}),[error,E]=useState(''),[loading,L]=useState(false),[drag,D]=useState(false);const root=useRef(null),epoch=useRef(0);
 useEffect(()=>{epoch.current++;Q(false);F([]);K([]);P([]);M(false);E('');L(false);},[workspace]);
 useEffect(()=>{onMenuChange(menu);if(!menu)return;const close=e=>{if(!root.current?.contains(e.target))M(false);};const key=e=>{if(e.key==='Escape')M(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[menu]);
 async function action(fn){const generation=epoch.current;L(true);E('');try{const value=await fn();if(generation!==epoch.current)return;return value;}catch(e){if(generation===epoch.current)E(e.message);}finally{if(generation===epoch.current)L(false);}}
 function add(next){if(!next)return;F(old=>{const all=[...old,...next].filter((v,i,a)=>a.findIndex(x=>x.path===v.path)===i);if(all.length>20){E('最多添加 20 个文件或文件夹');return old;}return all;});M(false);}
 async function choose(kind){const result=await action(()=>api.call('composer:pick',{kind}));add(result);}
 async function drop(e){e.preventDefault();D(false);if(busy||loading)return;if(securityMode){E('当前为安全测试模式，请直接描述目标 URL');return;}const paths=Array.from(e.dataTransfer.files).map(f=>api.filePath(f)).filter(Boolean);if(!paths.length){E('请从本机文件管理器拖入文件或文件夹');return;}add(await action(()=>api.call('composer:paths',{paths})));}
 async function capabilities(view){T(view);const value=await action(()=>api.call('composer:catalog'));if(value)C(value);}
 return <form ref={root} className={'task-composer'+(drag?' drag-active':'')} onSubmit={async e=>{e.preventDefault();if(busy||loading)return;const ok=await onSubmit(e,{files:files.map(f=>f.path),skills:selectedSkills.map(s=>s.path),plugins,...(securityMode?{mode:'security'}:{})});if(ok){F([]);K([]);P([]);M(false);}}} onDragOver={e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();if(!busy)D(true);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))D(false);}} onDrop={drop}>
 {securityMode&&<div className="context-chips"><span>◇ 安全测试 · S2-A<button type="button" disabled={busy} aria-label="退出安全测试模式" onClick={()=>Q(false)}>×</button></span></div>}{drag&&<div className="drop-hint">松开以添加本地文件或文件夹</div>}
 {(files.length>0||selectedSkills.length>0||plugins.length>0)&&<div className="context-chips">{files.map(f=><span key={f.path} title={f.path}>{f.kind==='folder'?'▱':'▤'} {f.name}<button type="button" disabled={busy} aria-label={'移除附件 '+f.name} onClick={()=>F(v=>v.filter(x=>x.path!==f.path))}>×</button></span>)}{selectedSkills.map(s=><span key={s.path} title={s.path}>◇ {s.name}<button type="button" disabled={busy} aria-label={'移除 Skill '+s.name} onClick={()=>K(v=>v.filter(x=>x.path!==s.path))}>×</button></span>)}{plugins.map(id=><span key={id}>⌁ {id}<button type="button" disabled={busy} aria-label={'移除插件 '+id} onClick={()=>P(v=>v.filter(x=>x!==id))}>×</button></span>)}</div>}
 <textarea aria-label="任务描述" placeholder={securityMode?'描述目标，例如：测试 https://example.com/，先查看响应头':'描述任务，或拖入文件与文件夹…'} rows={3} value={prompt} disabled={busy} onChange={e=>onPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form.requestSubmit();}}}/>
 {error&&<p role="alert" className="error">{error}</p>}
 <div className="compose-bottom"><div className="composer-context-control"><button type="button" aria-label="添加附件与能力" aria-haspopup="menu" aria-expanded={menu} disabled={busy||loading} onClick={()=>{T('root');M(v=>!v);}}>＋</button>{menu&&<div className="composer-menu" role="menu" aria-label="附件与能力">{tab==='root'?<><button type="button" role="menuitem" disabled={securityMode} onClick={()=>choose('file')}>▤ 添加文件</button><button type="button" role="menuitem" disabled={securityMode} onClick={()=>choose('folder')}>▱ 添加文件夹</button><hr/><button type="button" role="menuitem" onClick={()=>capabilities('plugins')}>⌁ 使用插件 <span>›</span></button><button type="button" role="menuitem" disabled={securityMode} onClick={()=>capabilities('skills')}>◇ 使用 Skill <span>›</span></button><small>添加本地引用，发送后由 Agent 按需读取。</small></>:<><button type="button" role="menuitem" onClick={()=>T('root')}>‹ 返回</button>{loading?<p>读取中…</p>:tab==='plugins'?<><button type="button" role="menuitem" onClick={()=>{Q(true);F([]);K([]);P([]);M(false);}}>◇ 安全测试 <span>S2-A</span></button><hr/>{catalog.plugins.map(p=><button type="button" role="menuitem" key={p.id} disabled={securityMode||!p.enabled} onClick={()=>{P(v=>v.includes(p.id)?v:[...v,p.id]);M(false);}}>{p.id}{!p.enabled?' · 未启用':''}</button>)}{!catalog.plugins.length&&<p>暂无插件，请在左侧设置中配置 MCP。</p>}</>:<>{catalog.skills.map(s=><button type="button" role="menuitem" key={s.path} title={s.path} onClick={()=>{if(selectedSkills.length>=10){E('最多选择 10 个 Skill');return;}K(v=>v.some(x=>x.path===s.path)?v:[...v,s]);M(false);}}>{s.name}</button>)}{!catalog.skills.length&&<p>暂无本地 Skill。支持项目及用户目录下的 .agents/skills 和 .codex/skills。</p>}</>}</>}</div>}</div>{children}</div></form>;
}
