import React,{useState,useEffect,useRef} from 'react';
const api=window.coagent;
function inline(text){return text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g).map((s,i)=>s.startsWith('`')?<code key={i}>{s.slice(1,-1)}</code>:s.startsWith('**')?<strong key={i}>{s.slice(2,-2)}</strong>:s);}
function Markdown({text}){
 const blocks=[];const lines=text.split('\n');let code=null;
 for(let i=0;i<lines.length;i++){const line=lines[i];if(line.startsWith('```')){if(code!==null){blocks.push(<pre key={i}><code>{code.join('\n')}</code></pre>);code=null;}else code=[];continue;}if(code!==null){code.push(line);continue;}const heading=/^(#{1,6})\s+(.*)/.exec(line);if(heading){blocks.push(React.createElement('h'+heading[1].length,{key:i},inline(heading[2])));continue;}if(/^\s*[-*]\s/.test(line)){const items=[];while(i<lines.length&&/^\s*[-*]\s/.test(lines[i])){items.push(<li key={i}>{inline(lines[i].replace(/^\s*[-*]\s/,''))}</li>);i++;}i--;blocks.push(<ul key={i}>{items}</ul>);}else if(line.trim())blocks.push(<p key={i}>{inline(line)}</p>);}
 if(code!==null)blocks.push(<pre key="end">{code.join('\n')}</pre>);return <div className="markdown-document">{blocks}</div>;
}
export function FilePanel({workspace}){
 const [tree,T]=useState({}),[expanded,X]=useState(new Set([''])),[preview,P]=useState(null),[source,S]=useState(false),[filter,F]=useState(''),[error,E]=useState('');const epoch=useRef(0),selection=useRef(0);
 async function load(path=''){const n=epoch.current;try{const value=await api.call('files',{path});if(n===epoch.current)T(v=>({...v,[path]:value}));}catch(e){if(n===epoch.current)E(e.message);}}
 async function show(path){const n=epoch.current,r=++selection.current;E('');try{const value=await api.call('preview',{path});if(n===epoch.current&&r===selection.current){P(value);S(false);}}catch(e){if(n===epoch.current&&r===selection.current)E(e.message);}}
 useEffect(()=>{epoch.current++;selection.current++;T({});X(new Set(['']));P(null);F('');E('');if(workspace)load();return()=>{epoch.current++;};},[workspace]);
 function toggle(path){const next=new Set(expanded);if(next.has(path))next.delete(path);else{next.add(path);if(!tree[path])load(path);}X(next);}
 function branch(path,depth=0){const listing=tree[path];return <>{listing?.entries.filter(e=>e.directory||!filter||e.name.toLowerCase().includes(filter.toLowerCase())).map(e=><React.Fragment key={e.path}><button className={'tree-entry '+(preview?.path===e.path?'selected':'')} style={{paddingLeft:12+depth*14}} title={e.path} onClick={()=>e.directory?toggle(e.path):show(e.path)} aria-expanded={e.directory?expanded.has(e.path):undefined}><span>{e.directory?(expanded.has(e.path)?'⌄':'›'):/\.md$/i.test(e.name)?'M↓':'▤'}</span>{e.name}</button>{e.directory&&expanded.has(e.path)&&branch(e.path,depth+1)}</React.Fragment>)}{listing?.truncated&&<small>仅显示前 300 项</small>}</>;}
 const markdown=/\.md(?:own)?$/i.test(preview?.path||'');
 return <section className="document-workspace"><div className="document-toolbar"><div className="document-breadcrumb" title={preview?.path||workspace}>{workspace?.split('/').at(-1)||'工作文件'}{preview?.path.split('/').map((part,i)=><span key={i}> › {part}</span>)}</div>{preview&&<><button onClick={()=>S(v=>!v)}>{source?'预览':'View source'}</button><button aria-label="关闭预览" onClick={()=>P(null)}>×</button></>}<button disabled={!workspace} onClick={()=>{for(const path of expanded)load(path);}}>刷新</button></div>{error&&<p role="alert">{error}</p>}<div className="document-body"><div className="document-content">{preview?(markdown&&!source?<Markdown text={preview.text}/>:<pre aria-label="文件内容">{preview.text}</pre>):<p className="muted">从右侧目录选择文件预览</p>}</div><div className="document-tree"><input aria-label="筛选文件" placeholder="筛选已展开目录中的文件…" value={filter} onChange={e=>F(e.target.value)}/><button className="tree-entry" onClick={()=>toggle('')} aria-expanded={expanded.has('')}>⌄ {workspace?.split('/').at(-1)||'未选择文件夹'}</button>{expanded.has('')&&branch('')}</div></div></section>;
}
