import React,{useEffect,useState} from 'react';
export function PluginsPanel(){
 const [config,C]=useState(null),[busy,B]=useState(false),[message,M]=useState(''),[inventory,I]=useState([]),[editing,E]=useState(false),[form,F]=useState({id:'',transport:'stdio',command:'',args:'[]',url:'',enabled:false});
 useEffect(()=>{window.coagent.call('plugins:status').then(r=>{C(r.config);M(r.warning||'');}).catch(e=>M(e.message));},[]);
 async function save(next){B(true);M('');try{const result=await window.coagent.call('plugins:save',next);C(result.config);I([]);E(false);M('插件配置已保存，下次任务连接时生效');}catch(e){M(e.message);}finally{B(false);}}
 async function discover(){B(true);M('');try{I(await window.coagent.call('plugins:discover'));M('已刷新 MCP 工具目录；不等同任务执行验证');}catch(e){M(e.message);}finally{B(false);}}
 if(!config)return <p role="status">{message||'读取插件配置…'}</p>;
 return <section><h2>插件与 MCP</h2><p className="muted">启用后，Agent 可调用服务提供的工具。MCP 程序在本机运行；本版不继承模型密钥，不导入个人浏览器登录状态。</p><div className="file-heading"><h3>MCP 服务</h3><button disabled={busy||editing} onClick={()=>{F({id:'',transport:'stdio',command:'',args:'[]',url:'',enabled:false});E(true);}}>添加 MCP 服务</button></div>{editing&&<form className="provider-editor" onSubmit={e=>{e.preventDefault();try{const server={...form,args:JSON.parse(form.args)};save({...config,servers:[...config.servers.filter(s=>s.id!==server.id),server]});}catch{M('参数必须为 JSON 字符串数组');}}}><label>服务标识<input required aria-label="MCP 服务标识" pattern="[-a-zA-Z0-9_]+" value={form.id} disabled={form.existing} onChange={e=>F(v=>({...v,id:e.target.value}))}/></label><label>传输方式<select aria-label="MCP 传输方式" value={form.transport} onChange={e=>F(v=>({...v,transport:e.target.value}))}><option value="stdio">本地 stdio</option><option value="http">Streamable HTTP</option></select></label>{form.transport==='stdio'?<><label>命令（绝对路径）<input required aria-label="MCP 命令" value={form.command} onChange={e=>F(v=>({...v,command:e.target.value}))}/></label><label>参数（JSON 数组）<textarea aria-label="MCP 参数" value={form.args} onChange={e=>F(v=>({...v,args:e.target.value}))}/></label></>:<label>服务 URL<input required aria-label="MCP URL" value={form.url} onChange={e=>F(v=>({...v,url:e.target.value}))}/></label>}<p className="muted">首版支持无鉴权服务；命令参数和 URL 中请勿填密钥。新增服务默认停用，保存后单独启用。</p><button disabled={busy}>保存 MCP 服务</button><button type="button" disabled={busy} onClick={()=>E(false)}>取消</button></form>}{config.servers.map(s=><div className="credential-card" key={s.id}><h3>{s.id} · {s.transport} · {s.enabled?'已启用':'已停用'}</h3><small>{s.url||s.command}</small><div><button disabled={busy} onClick={()=>save({...config,servers:config.servers.map(p=>p.id===s.id?{...p,enabled:!p.enabled}:p)})}>{s.enabled?'停用':'启用'} {s.id}</button><button disabled={busy||editing} onClick={()=>{F({...s,args:JSON.stringify(s.args||[]),existing:true});E(true);}}>编辑 {s.id}</button><button disabled={busy} onClick={()=>save({...config,servers:config.servers.filter(p=>p.id!==s.id)})}>删除 {s.id}</button></div></div>)}<button disabled={busy} onClick={discover}>刷新 MCP 工具</button>{inventory.map(s=><div className="credential-card" key={s.name}><strong>{s.name}</strong><p>{s.error||`${s.tools.length} 个工具`}</p><small>{s.tools.join(' · ')}</small></div>)}<p role="status">{busy?'正在处理…':message}</p></section>;
}
