import assert from 'node:assert/strict';
import {_electron as electron} from 'playwright';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';
import {testServer} from '../tests/helpers/http.js';
const root=await mkdtemp(join(tmpdir(),'coagent-project-ui-')),one=join(root,'alpha'),two=join(root,'beta');await mkdir(one);await mkdir(two);
const upstream=await testServer((_b,_q,res)=>{res.writeHead(200,{'content-type':'text/event-stream'});res.end(`data: {"choices":[{"index":0,"delta":{"content":"PROJECT_DONE"},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n`);});
const env:any={...process.env,COAGENT_TEST_USER_DATA:join(root,'user')};delete env.DEEPSEEK_API_KEY;delete env.QWEN_API_KEY;const app=await electron.launch({args:[resolve('dist/desktop/main.mjs')],env});
try{const page=await app.firstWindow();await page.waitForSelector('h1');const folders=[one,two];await app.evaluate(({dialog},folders)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[folders.shift()!]});},folders);
 const status=await page.evaluate(baseUrl=>(window as any).coagent.call('providers:save',{label:'Project fixture',baseUrl,protocol:'chat-completions',apiStyle:'openai',upstreamModel:'fixture',apiKey:'fixture-project-key'}),upstream.baseUrl);const model=status.models.find((m:any)=>m.custom).id;await page.evaluate(model=>(window as any).coagent.call('model',{id:model}),model);
 for(const [folder,prompt] of [[one,'alpha task'],[two,'beta task']] as const){await page.getByRole('button',{name:'＋ 新建任务'}).click();await page.locator('.project-list button.project').filter({hasText:folder.split('/').at(-1)!}).waitFor();await page.getByLabel('任务描述').fill(prompt);await page.getByRole('button',{name:'开始任务 ↑'}).click();await page.getByText('PROJECT_DONE',{exact:true}).waitFor();await page.locator('.badge').filter({hasText:'准备就绪'}).waitFor();}
 const projects=await page.evaluate(()=>(window as any).coagent.call('projects:list'));assert.deepEqual(projects.map((p:any)=>p.name),['beta','alpha']);assert.deepEqual(projects.map((p:any)=>p.tasks.length),[1,1]);assert.equal(await page.locator('.cards').count(),0);assert.equal(await page.locator('.project-group').count(),2);await page.getByRole('button',{name:'↻',exact:true}).click();await page.waitForTimeout(300);
 await page.locator('button.project').evaluateAll((buttons,path)=>{const button=buttons.find(b=>b.getAttribute('title')===path);if(!button)throw new Error('project button missing');(button as HTMLElement).click();},one);await page.waitForTimeout(500);const selected=await page.evaluate(()=>(window as any).coagent.call('state'));assert.equal(selected.workspace,one);await page.locator('.project-group').filter({hasText:'alpha'}).getByRole('button',{name:/alpha task/}).click();await page.getByText('PROJECT_DONE',{exact:true}).waitFor();
 await page.screenshot({path:'.verification/ui-projects-home.png',fullPage:true});await page.getByRole('button',{name:'设置',exact:true}).click();await page.getByText('Project fixture',{exact:true}).waitFor();await page.screenshot({path:'.verification/ui-projects-settings.png'});await page.locator('.settings-dialog').getByRole('button',{name:'浏览器',exact:true}).click();await page.getByText('允许 AI 控制内置浏览器',{exact:true}).waitFor();await page.screenshot({path:'.verification/ui-projects-browser-settings.png'});await page.locator('.settings-close').click();await page.getByRole('button',{name:'浏览器',exact:true}).click();await page.locator('.browser-toolbar').waitFor();await page.screenshot({path:'.verification/ui-projects-browser.png'});console.log('PROJECTS_UI=PASS folder_per_new_task=true grouped_by_folder=true tasks_1_1=true project_and_task_switch=true starter_cards_removed=true settings_reference_layout=true browser_chrome=true');
}finally{await app.close();await upstream.close();await rm(root,{recursive:true,force:true});}
